version: '2'
services:
  cubesviewer:
    image: epflsti/cubesviewer
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./var/cubesviewer.sqlite:/cubesviewer/cvapp/cubesviewer.sqlite
